mysql:
  username: ${DATABASE_MYSQL_USER:root}
  password:  ${DATABASE_MYSQL_PASSWORD:123456}
  schema: ${DATABASE_MYSQL_DATABASE:catalog}
  url: ${DATABASE_MYSQL_URL:localhost:3306}


spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none